version: 0.0.{build}
environment:
  matrix:
    - nodejs_version: "6"
image:
  - Visual Studio 2015
install:
  - ps: Install-Product node 8 x64
  # Sets Windows 7.1 SDK env vars.
  - set "PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%"
  - npm install -g npm node-gyp
  - set "PATH=%APPDATA%\npm;%PATH%"
  - node -v
  - npm -v
build: off
test_script:
  - cmd: npm test
