version: 0.0.{build}
environment:
  matrix:
    - nodejs_version: "6"
image:
  - Visual Studio 2015
install:
  - ps: Install-Product node 8 x64
  # Sets Windows 7.1 SDK env vars.
  - set "PATH=%ProgramFiles(x86)%\MSBuild\14.0\Bin;%PATH%"
  - npm install -g npm node-gyp
  - set "PATH=%APPDATA%\npm;%PATH%"
  - node -v
  - npm -v
  - set "WD=C:\msys64\usr\bin\"
  - set "MSYSTEM=MINGW64"
  - %WD%bash --login -c "cd $(cygpath '%cd%'); ""%~1"" ""%~2"" ""%~3"" ""%~4"" ""%~5"" ""%~6"" ""%~7"" ""%~8"" ""%~9"""
  - pacman -S --noconfirm mingw64/mingw-w64-x86_64-cairo
  - npm install
build: off
test_script:
  - cmd: npm test
